[versions]
# Plugins
shadow = "9.0.0-beta4"
spotless = "7.0.0.BETA4"
loom = "1.8-SNAPSHOT"
moddev = "2.0.73"
paperweight = "1.7.7"

# Mixins
mixin = "0.15.4+mixin.0.8.7"
mixinextras = "0.4.1"

# Tooling
kotlin-coroutines = "1.10.1"
kotlin-serialization = "1.8.0-RC"
guava = "33.4.0-jre"
slf4j = "2.0.16"

# Various
annotations = "24.1.0"
gson = "2.10"
prtree = "1.5"
caffeine = "3.1.8"

# Fabric - https://modmuss50.me/fabric.html
minecraft = "1.21.4"
fabric-loader = "0.16.9"
fabric-api = "0.110.5+1.21.4"

# Mods
sodium-fabric = "mc1.21.4-0.6.3-fabric"
sodium-neoforge = "mc1.21.4-0.6.3-neoforge"
modmenu = "13.0.0-beta.1"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
loom = { id = "fabric-loom", version.ref = "loom" }
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }

[libraries]
# Tooling
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlin-serialization" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
prtree = { group = "org.khelekore", name = "prtree", version.ref = "prtree" }

mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }

sodium-fabric = { group = "maven.modrinth", name = "sodium", version.ref = "sodium-fabric" }
sodium-neoforge = { group = "maven.modrinth", name = "sodium", version.ref = "sodium-neoforge" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }